Haven't really gotten anywhere.

diff --git a/HW2/tzachari_hw2/project_src/lib/hw2pass/run b/HW2/tzachari_hw2/project_src/lib/hw2pass/run
--- a/HW2/tzachari_hw2/project_src/lib/hw2pass/run
+++ b/HW2/tzachari_hw2/project_src/lib/hw2pass/run
@@ -10,6 +10,12 @@ rm llvmprof.out # Otherwise your profile runs are added together
 
 clang -emit-llvm -o correct$1.bc -c correct$1.c || { echo "Failed to emit llvm bc"; exit 1; }
 
+opt -dot-cfg correct$1.bc > /dev/null
+
+mv cfg.main.dot correct$1.dot
+
+xdot correct$1.dot &
+
 opt -loop-simplify < correct$1.bc > correct$1.ls.bc || { echo "Failed to opt loop simplify"; exit 1; }
 
 opt -insert-edge-profiling correct$1.ls.bc -o correct$1.profile.ls.bc
@@ -18,9 +24,9 @@ llc correct$1.profile.ls.bc -o correct$1.profile.ls.s
 
 g++ -o correct$1.profile correct$1.profile.ls.s /opt/llvm/Release+Asserts/lib/libprofile_rt.so 
 
-time ./correct$1.profile  > /dev/null
+./correct$1.profile  > /dev/null
 
-opt -load ../Release+Asserts/lib/hw2pass.so -lamp-insts -insert-lamp-profiling -insert-lamp-loop-profiling -insert-lamp-init < correct$1.ls.bc > correct$1.lamp.bc || { echo "Failed to opt load"; exit 1; }
+opt -load ../Release+Asserts/lib/hw2pass.so -licm -lamp-insts -insert-lamp-profiling -insert-lamp-loop-profiling -insert-lamp-init < correct$1.ls.bc > correct$1.lamp.bc || { echo "Failed to opt load"; exit 1; }
 
 llc < correct$1.lamp.bc > correct$1.lamp.s || { echo "Failed to llc"; exit 1; }
 
@@ -31,7 +37,16 @@ g++ -o correct$1.lamp.exe correct$1.lamp.s ../tools/lamp-profiler/lamp_hooks.o |
 echo " "
 echo "**************** LAMP ****************"
 echo "Done generating lamp profile"
-opt -load ../Release+Asserts/lib/hw2pass.so -lamp-inst-cnt -lamp-map-loop -lamp-load-profile -profile-loader -profile-info-file=llvmprof.out -slicm < correct$1.ls.bc > correct$1.slicm.bc || { echo "Failed to opt-load"; exit 1; }
+#opt -load ../Release+Asserts/lib/hw2pass.so -licm < correct$1.ls.bc > correct$1.slicm.bc || { echo "Failed to opt-load"; exit 1; }
+#opt -load ../Release+Asserts/lib/hw2pass.so -lamp-inst-cnt -lamp-map-loop -lamp-load-profile -profile-loader -profile-info-file=llvmprof.out -slicm < correct$1.ls.bc > correct$1.slicm.bc || { echo "Failed to opt-load"; exit 1; }
+
+opt -load ../Release+Asserts/lib/hw2pass.so -licm -lamp-inst-cnt -lamp-map-loop -lamp-load-profile -profile-loader -profile-info-file=llvmprof.out -slicm -licm < correct$1.ls.bc > correct$1.slicm.bc || { echo "Failed to opt-load"; exit 1; }
+
+opt -dot-cfg correct$1.slicm.bc >& /dev/null
+
+mv cfg.main.dot correct$1.slicm.dot
+
+xdot correct$1.slicm.dot &
 
 llc < correct$1.slicm.bc > correct$1.slicm.s
 
